#define SHOOTER_VOLTAGE_COMPENSATION 11.0

#define SHOOTER_MOTOR_LEFT_CAN_ID 12
#define SHOOTER_MOTOR_RIGHT_CAN_ID 11
#define HOOD_MOTOR_CAN_ID 10
#define TURRET_MOTOR_CAN_ID 9
#define CONVEYOR_MOTOR_CAN_ID 7
#define FEEDER_MOTOR_CAN_ID 8
#define INTAKE_MOTOR_CAN_ID 6
#define DRIVETRAIN_MOTOR_RIGHT_CAN_ID 1
#define DRIVETRAIN_MOTOR_RIGHT_FOLLOWER_CAN_ID 2
#define DRIVETRAIN_MOTOR_LEFT_CAN_ID 3
#define DRIVETRAIN_MOTOR_LEFT_FOLLOWER_CAN_ID 4

#define INTAKE_SOLENOID_ID_FORWARD 0
#define INTAKE_SOLENOID_ID_REVERSE 1

#define HOOD_ENCODER_ID_A 12
#define HOOD_ENCODER_ID_B 13
#define TURRET_ENCODER_ID_A 8
#define TURRET_ENCODER_ID_B 9

#define INTAKE_MOTOR_SPEED 0.7
#define CONVEYOR_MOTOR_SPEED 0.7
#define FEEDER_MOTOR_SPEED 0.9
